name: Nightfall DLP Action
description: Scan Pull Requests for sensitive information, like credentials & secrets, PII, credit card numbers, and more.
runs:
  using: 'docker'
  image: 'docker://nightfallai/nightfall_code_scanner:TestClientFix'
branding:
  icon: 'eye'
  color: 'purple'
